login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development: &development
  database: refinerycms_dev
  <<: *login

test: &test
  database: refinerycms_test
  <<: *login

production: &production
  adapter: mysql2
  host: localhost
  database: refinerycms_prod
  username: root
  password: 
